/*******************************************************************************************************
 * @description       : Constants class for static values
 * @author            : Rahul Panditrao
 * @last modified on  : 30-12-2022
 * @last modified by  : Rahul Panditrao
 * -----------------------------------------------------------------------------------------------------
 * Developer            Date               Description
 * -----------------------------------------------------------------------------------------------------
 * Rahul Panditrao     30-12-2022         Initial Version
******************************************************************************************************/
public with sharing class Constants {
    public static final String sobjectTypeMissmatch = 'Sobject type missmatch.';
    public static final String COLON = ':';
    public static final String COMMA = ',';
    public static final String NEWLINE = '\n';
    public static final String JSON_KEY_SELECTEDPRODUCTS = 'selectedproducts';
    
    public static final String SINGLE_QUOTE = '\'';
    public static final String DML_INSERT = 'Insert';
    public static final String DML_UPDATE = 'Update';
    public static final String FLD_ACCOUNTID = 'AccountId';
    public static final String FLD_PRODUCT2ID = 'Product2Id';
    public static final String FLD_STAGENAME = 'StageName';
    public static final String FLD_CLOSEDATE = 'CloseDate';
    public static final String FLD_PRICEBOOK2ID = 'Pricebook2Id';
    public static final String FLD_QUANTITY = 'Quantity';
    public static final String FLD_NAME = 'Name';
    public static final String FLD_LASTNAME = 'LastName';
    

    public static final String SOBJECT_LEAD = 'Lead';
    public static final String SOBJECT_ACCOUNT = 'Account';
    public static final String SOBJECT_OPPORTUNITYLINEITEM = 'OpportunityLineItem';
    public static final String SOBJECT_OPPORTUNITY = 'Opportunity';
    public static final String SOBJECT_PRODUCT = 'Product2';
}